spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_service_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: rachidbenkitou2021@gmail.com
    password: kxmd uimm jntc qxqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true